### ISSUE TITLE
Get event data from file in `FakeListener`

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/beamlime#154]
Follow-up to #153. Instead of generating noise, we can do better if we have a NeXus file that was created from a particular run-start JSON.

- Use ScippNexus new label-based indexing to read chunks of event data (from all `NXevent_data` groups).
- Chunk length should correspond to the "accumulation window" of the listener, i.e., a few seconds (may later be configurable).
- Do some minor conversion/renaming so the read data matches the raw JSON.

Unchanged (this should happen already in the current implementation): Send update messages with nested structure. Same as in #153 but now with real data instead of noise.

**Comment by YooSunYoung** [comment]
@SimonHeybrock  I just asked George about that, and they were developing this tool
https://github.com/ess-dmsc/nexus-json
that reproduce the json template from a file.

He said the goal is to reproduce 100% same template file from a nexus file, so that they can feed it again.
Currently they are still developing, but maybe good enough to generate an example file we need for now...?
