### ISSUE TITLE
Do not use explicit topic partitions?

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/beamlime#274]
There is some code in Beamlime that finds all partitions of a topic and explicitly sets the consumer to use these. Since we do not intend to use consumer groups (I think), shouldn't it be sufficient to not set any partitions? As far as I understand we should then get messages from all partitions automatically.

**Comment by YooSunYoung** [comment]
Because it's much slower if you don't manually assign any partitions.
Maybe we can make it faster by changing the broker setting though. I haven't tried.

I wrote this down in the dmsc docs before:
https://docs.docs.esss.dk/dmsc/groups/dram/data-reduction/data-streaming.html#assign-topicpartition-to-a-consumer-manually-and-do-not-subscribe

**Comment by SimonHeybrock** [comment]
Thanks @YooSunYoung, this fixed some startup lag I was experiencing and did not understand in my Kafka service proof-of-concept!
